### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by andrew** [Rumyra/browserapis.wtf#27]
Add a file called `Contributing.md` and Github will show it to anyone opening an issue or pull request: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by varjmes** [comment]
I'd like to help with this. Will start writing something, if that's ok?

**Comment by andrew** [comment]
Brilliant, thanks @Charlotteis!

**Comment by varjmes** [comment]
Done! ^
