### ISSUE TITLE
Looks weird in Firefox Dev Edition

### ISSUE THREAD

**Issue by Rumyra** [Rumyra/browserapis.wtf#49]
I wouldn't say this was a priority - also I think it looks cool

https://www.dropbox.com/s/jn3g2d2wbyjet7j/Screenshot%202015-11-30%2014.51.48.png?dl=0

**Comment by omgmog** [comment]
Looks weird in all editions of Firefox... :grin:

**Comment by kumar303** [comment]
Thanks for fixing! Will this be released to the live site soon? http://browserapis.wtf/ Hard refreshing the cache still shows the vertical column layout.

**Comment by Rumyra** [comment]
Yes @kumar303 this is all merged I just haven't done a deploy yet - I wanted to add a few things myself first :) I'll be doing it some time this weekend
