### ISSUE TITLE
Which w3 status details to use?

### ISSUE THREAD

**Issue by dougaitken** [Rumyra/browserapis.wtf#64]
Just getting into this project, I think it's great.

However, I've noticed that some APIs use the main w3.org article, but the exampleapi.html.md says `w3c_link: http://githublinkhere.com` 

Does this mean the https://w3c.github.io site or published version on w3.org?

**Comment by Rumyra** [comment]
Thery're one in the same, so either are ok, but I guess it should probably be the w3.org - thanks for flagging :)
